services:
  accounts:
    image: mad20huri/accounts:v1
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mad
  loans:
    image: mad20huri/loans:v1
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mad
  cards:
    image: mad20huri/cards:v1
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mad
networks:
  mad:
    driver: "bridge"
